import React from 'react'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './css/globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { AuthProvider } from '@/context/AuthContext'
import { ToastProvider } from '@/context/ToastContext'
import { BrandingProvider } from '@/context/BrandingContext'
import SWRProvider from '@/components/providers/SWRProvider'

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'MatDash-Nextjs-Free',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <link rel='icon' href='/favicon.svg' type='image/svg+xml' />
        {/* {typeof window !== 'undefined' && <ThemeModeScript />} */}
      </head>
      <body className={`${manrope.className}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <SWRProvider>
            <BrandingProvider>
              <ToastProvider>
                <AuthProvider>{children}</AuthProvider>
              </ToastProvider>
            </BrandingProvider>
          </SWRProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
